version: '3'

name: my-atm

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: my-atm
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./e2e-init-db.sql:/docker-entrypoint-initdb.d/e2e-init-db.sql
