name: Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test-backend:
    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: my-atm-e2e
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install -g pnpm && pnpm i
      - name: Copy .env.example to .env
        run: |
          chmod +x ./setup.sh
          ./setup.sh
      - name: Unit test backend
        run: pnpm frontend test:unit:cov
      - name: E2E test backend
        env:
          ENV: e2e
        run: pnpm frontend test:e2e:cov

  test-frontend:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install -g pnpm && pnpm i
      - name: Copy .env.example to .env
        run: |
          chmod +x ./setup.sh
          ./setup.sh
      - name: Test frontend
        run: pnpm frontend test

  playwright:
    needs: [test-frontend, test-backend]
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install -g pnpm && pnpm i
      - name: Copy .env.example to .env
        run: |
          chmod +x ./setup.sh
          ./setup.sh
      - name: Build frontend
        run: pnpm frontend build
      - name: Build backend
        run: pnpm frontend build
      - name: Run Playwright tests
        run: pnpm playwright test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: apps/playwright/playwright-report
          retention-days: 7
